# Generated by Django 2.0.10 on 2019-01-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='newfield',
            field=models.CharField(default='pages....', max_length=140),
        ),
    ]
