# Generated by Django 2.0.10 on 2019-01-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_newfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='newfield',
            field=models.TextField(default='pages....'),
        ),
    ]
